name: op
favicon: null
layout_spectrum: 0.74887
typography_spectrum: 0.54245
title: op2
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.9975712175946683
purpose: []
